dateModified: 1618163023
email:
  fromEmail: marshall@authenteak.com
  fromName: authenTEAK
  transportType: craft\mail\transportadapters\Sendmail
system:
  edition: solo
  live: true
  name: authenTEAK
  schemaVersion: 3.6.7
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
